//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takochu.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takochu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;!-- SMG1/2 Object Database, generated 03/11/2022 20:05:04 --&gt;
        ///
        ///&lt;database timestamp=&quot;1647029104&quot;&gt;
        ///
        ///	&lt;actors&gt;
        ///	&lt;actor id=&quot;Air&quot;&gt;
        ///		&lt;flags known=&quot;0&quot; complete=&quot;0&quot;/&gt;
        ///	&lt;fields&gt;
        ///	&lt;/fields&gt;
        ///	&lt;/actor&gt;
        ///
        ///	&lt;actor id=&quot;AnmModelSwitchMove&quot;&gt;
        ///		&lt;flags known=&quot;0&quot; complete=&quot;0&quot;/&gt;
        ///	&lt;fields&gt;
        ///	&lt;/fields&gt;
        ///	&lt;/actor&gt;
        ///
        ///	&lt;actor id=&quot;AnmModelSwitchMoveEndKill&quot;&gt;
        ///		&lt;flags known=&quot;0&quot; complete=&quot;0&quot;/&gt;
        ///	&lt;fields&gt;
        ///	&lt;/fields&gt;
        ///	&lt;/actor&gt;
        ///
        ///	&lt;actor id=&quot;AnmModelSwitchMoveEndKillAnyAnim&quot;&gt;
        ///	 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string objectdb {
            get {
                return ResourceManager.GetString("objectdb", resourceCulture);
            }
        }
    }
}
